### PR TITLE
Add test for X-Clacks-Overhead header (GNU Terry Pratchett)

### PR DESCRIPTION
**Pull request by ineffyble**
Adds a test for the [X-Clacks-Overhead](http://www.gnuterrypratchett.com/) HTTP header, a tribute to the late Sir Terry Pratchett.

### CODE REVIEW

**Comment by ticky** [comment]
This is cute but given the requirement to keep size to a minimum in a bookmarklet, I don’t think it’s something I’d like to add. Thanks, though!

**Comment by ineffyble** [comment]
That's fair enough. That said, depending on how big the project grows, it
may be worth considering a remote injection option (where the bookmarket
adds a script tag defending the latest version of the JS file on GitHub).

**Comment by ticky** [comment]
Remote injection is an interesting idea, but it seems that with more and more sites using restrictive `Content-Security-Policy` directives, it’s becoming a less and less viable option. At a certain scale I’d probably consider making this a browser extension instead.

**Comment by ineffyble** [comment]
*nod* I'm doing a decent amount of browser extension dev these days, so can probably assist. Thanks to Mozilla's creation of WebExtensions, you can in theory create a single extension that works on Chrome, Firefox, Opera, and Edge(O_O).

**Pull request closed without merging**
